spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    default-schema: publicinfo
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      audit: audit-publicinfo
    consumer:
      group-id: public-info
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.bank.publicinfo.dto"
        spring.json.value.default.type: com.bank.publicinfo.dto.BankDetailsDto