apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-info-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: public-info.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: public-info-service
                port:
                  number: 80